name: build docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker login -u jayfong -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -f ./Dockerfile -t jayfong/nsfw-api:latest .
          docker push jayfong/nsfw-api:latest
